export const FETCH_CONFIGS_START = 'FETCH_CONFIGS_START';
export const FETCH_CONFIGS_SUCCESS = 'FETCH_CONFIGS_SUCCESS';
export const FETCH_CONFIGS_FAILURE = 'FETCH_CONFIGS_FAILURE';

export const DELETE_CONFIG_START = 'DELETE_CONFIG_START';
export const DELETE_CONFIG_SUCCESS = 'DELETE_CONFIG_SUCCESS';
export const DELETE_CONFIG_FAILURE = 'DELETE_CONFIG_FAILURE';
