export const SET_DATA = 'SET_DATA';
export const SET_SELECTED_DATA = 'SET_SELECTED_DATA';

export const SET_PREDICTION_MODE = 'SET_PREDICTION_MODE';
export const SET_DISPLAYED_PREDICTION = 'SET_DISPLAYED_PREDICTION';

export const FETCH_ARIMA_PREDICTION_START = 'FETCH_ARIMA_PREDICTION_START';
export const FETCH_ARIMA_PREDICTION_SUCCESS = 'FETCH_ARIMA_PREDICTION_SUCCESS';
export const FETCH_ARIMA_PREDICTION_FAILURE = 'FETCH_ARIMA_PREDICTION_FAILURE';

export const FETCH_VAR_PREDICTION_START = 'FETCH_VAR_PREDICTION_START';
export const FETCH_VAR_PREDICTION_SUCCESS = 'FETCH_VAR_PREDICTION_SUCCESS';
export const FETCH_VAR_PREDICTION_FAILURE = 'FETCH_VAR_PREDICTION_FAILURE';

export const FETCH_WHITE_NOISE_TEST_START = 'FETCH_WHITE_NOISE_TEST_START';
export const FETCH_WHITE_NOISE_TEST_SUCCESS = 'FETCH_WHITE_NOISE_TEST_SUCCESS';
export const FETCH_WHITE_NOISE_TEST_FAILURE = 'FETCH_WHITE_NOISE_TEST_FAILURE';

export const FETCH_STATIONARITY_TEST_START = 'FETCH_STATIONARITY_TEST_START';
export const FETCH_STATIONARITY_TEST_SUCCESS = 'FETCH_WHITE_STATIONARITY_SUCCESS';
export const FETCH_STATIONARITY_TEST_FAILURE = 'FETCH_WHITE_STATIONARITY_FAILURE';

export const FETCH_CAUSALITY_TEST_START = 'FETCH_CAUSALITY_TEST_START';
export const FETCH_CAUSALITY_TEST_SUCCESS = 'FETCH_CAUSALITY_TEST_SUCCESS';
export const FETCH_CAUSALITY_TEST_FAILURE = 'FETCH_CAUSALITY_TEST_FAILURE';

export const ADD_ENTRY_TO_PREDICTION_HISTORY = 'ADD_ENTRY_TO_PREDICTION_HISTORY';
