"""empty message

Revision ID: 1e897de317bc
Revises: 84c55f1a5b88
Create Date: 2024-05-31 16:25:06.268881

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1e897de317bc'
down_revision = '84c55f1a5b88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prediction_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('input_data', postgresql.JSON(astext_type=sa.Text()), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prediction_history', schema=None) as batch_op:
        batch_op.drop_column('input_data')

    # ### end Alembic commands ###
