"""empty message

Revision ID: 62070a21c44d
Revises: 889b284aade7
Create Date: 2024-05-17 11:11:29.914757

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '62070a21c44d'
down_revision = '889b284aade7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuration_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('configuration_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('prediction_mode', sa.String(length=10), nullable=False),
    sa.Column('selected_data_boundaries', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('test_prediction_parameters', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('real_prediction_parameters', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('test_prediction', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('real_prediction', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('last_train_point', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('evaluation', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id', 'configuration_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('configuration_history')
    # ### end Alembic commands ###
