"""empty message

Revision ID: 84c55f1a5b88
Revises: 9ad5000525cb
Create Date: 2024-05-20 13:24:19.072685

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '84c55f1a5b88'
down_revision = '9ad5000525cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prediction_history', schema=None) as batch_op:
        batch_op.alter_column('selected_data_boundaries',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prediction_history', schema=None) as batch_op:
        batch_op.alter_column('selected_data_boundaries',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)

    # ### end Alembic commands ###
