"""empty message

Revision ID: 889b284aade7
Revises: 
Create Date: 2024-05-11 14:42:48.504792

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '889b284aade7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('value_properties', postgresql.JSON(astext_type=sa.Text()), nullable=False))
        batch_op.add_column(sa.Column('time_property', postgresql.JSON(astext_type=sa.Text()), nullable=False))
        batch_op.alter_column('data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuration', schema=None) as batch_op:
        batch_op.alter_column('data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
        batch_op.drop_column('time_property')
        batch_op.drop_column('value_properties')

    # ### end Alembic commands ###
