"""empty message

Revision ID: 91b3921bc37f
Revises: 1e897de317bc
Create Date: 2024-06-18 15:03:09.545378

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '91b3921bc37f'
down_revision = '1e897de317bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prediction_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stationarity_test', postgresql.JSON(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('white_noise_test', postgresql.JSON(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('causality_test', postgresql.JSON(astext_type=sa.Text()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prediction_history', schema=None) as batch_op:
        batch_op.drop_column('causality_test')
        batch_op.drop_column('white_noise_test')
        batch_op.drop_column('stationarity_test')

    # ### end Alembic commands ###
