"""empty message

Revision ID: 9ad5000525cb
Revises: 62070a21c44d
Create Date: 2024-05-17 15:52:11.845314

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9ad5000525cb'
down_revision = '62070a21c44d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prediction_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('configuration_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('prediction_mode', sa.String(length=10), nullable=False),
    sa.Column('selected_data_boundaries', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('test_prediction_parameters', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('real_prediction_parameters', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('test_prediction', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('real_prediction', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('last_train_point', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('evaluation', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['configuration_id'], ['configuration.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('configuration_history')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuration_history',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('configuration_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('prediction_mode', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('selected_data_boundaries', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('test_prediction_parameters', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('real_prediction_parameters', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('test_prediction', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('real_prediction', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('last_train_point', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('evaluation', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'configuration_id', name='configuration_history_pkey')
    )
    op.drop_table('prediction_history')
    # ### end Alembic commands ###
