"""empty message

Revision ID: eab324e64874
Revises: 91b3921bc37f
Create Date: 2024-06-28 17:20:04.903719

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'eab324e64874'
down_revision = '91b3921bc37f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prediction_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('train_extent', postgresql.JSON(astext_type=sa.Text()), nullable=False))
        batch_op.drop_column('last_train_point')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prediction_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_train_point', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
        batch_op.drop_column('train_extent')

    # ### end Alembic commands ###
